# Generated by Django 4.1.2 on 2024-03-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
